linux, glibc 2.2.5: fix pthread not found
Fix this error:

CMakeFiles/qute.dir/watched_literal_propagator.cc.o  -o ../qute
-lboost_program_options-mt -lboost_thread-mt -lboost_log-mt
-lboost_system-mt -lboost_chrono-mt -lboost_date_time-mt
-lboost_atomic-mt -lboost_log_setup-mt -lboost_filesystem-mt
-lboost_regex-mt
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/qute.dir/main.cc.o:
undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
//home/linuxbrew/.linuxbrew/lib/libpthread.so.0: error adding symbols:
//DSO missing from command line
collect2: error: ld returned 1 exit status